#!/usr/bin/env sh

# Unload the macOS WindowManager process
launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist > /dev/null 2>&1 &

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=display_added action="sleep 2 && $HOME/.config/yabai/create_spaces.sh"
yabai -m signal --add event=display_removed action="sleep 1 && $HOME/.config/yabai/create_spaces.sh"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"
#
# yabai -m signal --add event=window_created app="KakaoTalk" title!="KakaoTalk" action="yabai -m window --insert stack"
# yabai -m signal --add event=window_created app="KakaoTalk" title="KakaoTalk" action="yabai -m window --insert east"

# yabai -m signal --add event=window_destroyed app="(Chrome|Alacritty|KakaoTalk|Slack|Notion)" action="yabai -m window --focus last"
# yabai -m signal --add event=application_terminated app="(Chrome|Alacritty|KakaoTalk|Slack|Notion)" action="yabai -m window --focus last"

$HOME/.config/yabai/create_spaces.sh

yabai -m config external_bar               all:38:0     \
                window_border              on           \
                mouse_follows_focus        off          \
                focus_follows_mouse        off          \
                window_zoom_persist        off          \
                window_placement           first_child \
                window_topmost             off          \
                window_shadow              float        \
                window_opacity             off          \
                window_opacity_duration    0.0          \
                active_window_opacity      1.0          \
                normal_window_opacity      0.0          \
                window_border_width        2            \
                window_border_hidpi        off          \
                window_border_radius       11           \
                window_border_blur         off          \
                window_animation_duration  0.0          \
                active_window_border_color 0xffe1e3e4   \
                normal_window_border_color 0xff494d64   \
                insert_feedback_color      0xff9dd274   \
                split_ratio                0.50         \
                auto_balance               off          \
                mouse_modifier             fn           \
                mouse_action1              move         \
                mouse_action2              resize       \
                mouse_drop_action          swap         \
                                                        \
                top_padding                10           \
                bottom_padding             4            \
                left_padding               4            \
                right_padding              4            \
                window_gap                 6


# yabai -m config insert_feedback_color 0x00FFFFFF

yabai -m config layout float

# Exclude problematic apps from being managed:
# yabai -m rule --add app="^(LuLu|Calculator|Software Update|Dictionary|VLC|Settings|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|App Store|Steam|Alfred|Activity Monitor)$" manage=off
# yabai -m rule --add app="^Docker Desktop$" manage=off
# yabai -m rule --add app="^(System Information|System Settings|System Preferences)" manage=off mouse_follows_focus=on
# yabai -m rule --add app="^Finder" manage=off
# yabai -m rule --add app="^Fig" manage=off
# yabai -m rule --add app="^Tunnelblick" manage=off
# yabai -m rule --add app="^BuhoCleaner" manage=off
# yabai -m rule --add app="^AltTab" manage=off
# yabai -m rule --add app!="^(Notion|KakaoTalk|Slack|Chrome|Alacritty)" manage=off

# Manage apps with custom settingsy$" space=^2
#
# yabai -m rule --add app="^Notion$" mouse_follows_focus=on
# yabai -m rule --add app="^KakaoTalk$" mouse_follows_focus=on
# yabai -m rule --add app="^Slack$" mouse_follows_focus=on

# yabai -m rule --add app="^Chrome$" mouse_follows_focus=on
# yabai -m rule --add app="^Alacritty$" mouse_follows_focus=on
# yabai -m rule --add app="^Finder$" mouse_follows_focus=on

# yabai -m signal --add event=window_created action='stack2'
# yabai -m signal --add event=window_moved action='stack2'


echo "yabai configuration loaded.."
